language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 3hA/UOMX7yfQoGFbcXrrzkKfXjim1ElQs9RxghogzOnLrVITD5NuLAp0vkVGbyNwSNzaCd4/Z/+b3PZiQVZb3msTrRWz1GCJagsHKq/48XScRuKobpAe8RArPRb5DP8cIHn4S3xYt9xfAj1Mqrjf7LCA4NE21C1EFbUVGXeyq+tfbxzIa+55ZbXmxHvKh/V93/XlxQqqNyXhIOIZIOTOn6MU1x605H1qZwbj4LkjobdGIzz2v0PBmvkIoBir9XJx3VgBxKU+AbQd3grR1vU2A75pJfI9GgE14XilRmY8at1vjDxTKPz9L2EWyBxHZWHvyETCs9o0Y8czAoet53k+KljdsREN7XId2OqBrF2LGPx/19vnRo9f0JKkL7vvihGYPl3JrJD8fm2nvnCAwlqP1rlb/aSmOyPEGw/x3CehzNX4LZPrLrtKUNGH+rshcUUd/QxE3y6eVzqjEFKYVDBTF5QRUtkX9eeD73d7ZMh2BxnutrZJF0D7sObtOL3DlrtkG50Pxjw8bsfnAbsVYwpycxFQ1XnRtqgDMQkjAV2NWYGn2eeonoOKd/dgV1pJss46jBKMIPK913bUg42boFlzpmB7uX2YrHYL1OO/WDQ/eBfgNCMHmQizrE5nPZZ0lPfKlfFXTPueWMA13VZLgBGlwdTKMqvvspoKRIz8uklhJas=
  app: react-hot-cold
  on:
    repo: maryzhenghan/react-hot-cold
