language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: F40eJuz22vl4Q7j3U1CIwhK8HWS1y5TCzwKncqekefYnsQV/0yYRGZNgGEMQh3nRk6jf3PXlFRAedYW1aQFdPa6OVIYU+owr7orLxXz2mfJC+BG5L8hvx+VBU5OuXri3qDJ3Ytu1xKsnI4OGCa1VGWXiVCqVae39ZJO+5/OvbnXvAyZ9WdL0kM5Ee7lsV+YkNjpBvWDxFi2I0hxWTZlhQ77Bosyh/wmtKdr6Nm/2FpCwgLJrYjjAm5gg9drI/ExLr90iyVX3B+BfV1DUevW/hNGASUd0Tt5DL7pIDbTnwlMUcT00I2xkxmGZ2NkPyzI//c1kAOR2B9q21vFumHNRqG27M6dJ4ktXhN4yAVxbbiysxbcyzo2B/M+9TAR+V//l/G5MBsksaz867tFWWIP5wcxJ5OER36hm5eyo8SB59Hu3+zOMk/QO+8PMw6qTqwHEAiY7uvMUwzYhAFf99Ti4JdRvMCy5+RVRPOyXbQibxY2iKtGM6onRmUP4D3my41RPODybXalChmzDjmk1TgNcJJfwq8mUJfOoPKH9ESbObK+ghyDZ8XPtHdqYvqXGGqMk6Sbyq04wPv7Y8MEgucmTe9A5PtNfOE0ymm5IMz7AztFF/LWWcS8nwRre+HhzYUtWVTbCqfIpSL9WlpFkbAv8fgJzktESkZlZ1GP+4cp9CjE=
  app: infinite-fjord-45931
  on:
    repo: maryzhenghan/react-hot-cold
